version: '3.8'
services:
  api:
    build:
      context: .
      # Remove target: development since it does not exist.
      # If you want to use the production stage for API during development, you can leave it out.
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - backend

  importer:
    build:
      context: .
      target: production # Use the production stage for the importer.
    command: ['node', 'seed.js']
    env_file:
      - .env
    environment:
      PGHOST: postgres
      PGUSER: ${DB_USERNAME}
      PGPASSWORD: ${DB_PASSWORD}
      PGDATABASE: ${DB_NAME}
      PGPORT: 5432
    volumes:
      - ./companies_converted.json:/usr/src/app/companies_converted.json:ro
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: prabinnepal1996@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - backend

networks:
  backend:
